#!/bin/bash
# Launching script for demo 1 of HTTP-infra lab
# Can be run on branch 

# To start, we kill and remove all docker containers in order to avoid conflicts

docker kill $(docker ps -q)
docker rm $(docker ps -a -q)

# Then, we build our docker image

echo "Building docker container"

docker build -t res/apache_php ../docker-images/apache-php-image/.

# And finally, we run our docker container with a port mapping from 8080 to 80

echo "Launching docker container"

docker run -d -p 8080:80 --name apache-static res/apache_php